name: Docker Publish

on:
  push:
    tags: 
        - "v*"
  workflow_dispatch:
jobs:
 
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      
    - name: "Login to Docker hub"
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: "Build and push image tags"
      uses: "docker/build=push-action@v5"
      with:
        context: "*"
        push: true
        tags: |
           "${{ github.repository }}:latest"
           "${{ github.repository }}:${{ github.ref_name }}
      
    
