name: Docker Image CI

on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Extract version and set it to tag
        run: |
             echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: araheemcis/numberadd
          tags: |
               ${{ vars.DOCKERHUB_USERNAME }}:latest
               ${{ vars.DOCKERHUB_USERNAME }}:${{ env.TAG }}
          registry: docker.io
          #dockerfile: Dockerfile.ci
          username: ${{ vars.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_TOKEN }}

