name: Docker Image CI

on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker Build and push 
        uses: docker/build-push-action@v4    
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/project1:${{ github.sha }}          
          
    

