name: "Docker Publish for tags "
on:
  push:
    tags: 
       - "*"
  #workflow_dispatch:
jobs:
 
  build-and-push-with-tags:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      
    - name: "Login to Docker hub"
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Set up QEMU"
      uses: "docker/setup-qemu-action@v3"
    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v3"
          
    - name: "Build and push image tags"
      uses: "docker/build-push-action@v6"
      with:
         push: true
         tags: |
           "${{ github.repository }}:${{ github.ref_name }}"

    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
          repository: araheemcis/k8-repo

           
    - name: Update values.yaml
      run: |
          ls
          cd helm/project1-chart
          sed -i 's|tag:.*|tag: '${{ github.ref_name }}'|' values.yaml 
          git config --global user.name 'Abdul Raheem'
          git config --global user.email 'araheemcis@gmail.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push

